### ISSUE TITLE
OCS pizzeria does not bring me a pizza

### ISSUE THREAD

**Issue by dbanck** [ocs/OpenCityStreets#1]
Hey

I build a pizzeria at my local town, but I didnt get a pizza.
I'm waiting here for ours now and no delivery guy is ringing.
This hunger is killing me :(

Please fix this in next version!

**Comment by codecat** [comment]
Get some people to work! :P

**Comment by aaronwolfe** [comment]
actually, i accepted the pizza that was offered to you, using a bug in the API.  now i have the pizza and the money.

**Comment by codecat** [comment]
Totally fixed!
